zalando-stups/java-sproc-wrapper

src/main/java/de/zalando/typemapper/postgres/PgArray.java, src/test/java/de/zalando/typemapper/postgres/PgArrayTest.java
https://github.com/zalando/java-sproc-wrapper/issues/7
=> Fix issue 7: equals & hashCode impl for PgArray

pom.xml, src/test/java/de/zalando/typemapper/core/fieldMapper/DateFieldMapperTest.java, src/test/java/de/zalando/typemapper/postgres/PgSerializerTest.java
Tested in GMT and India (which has 30 minute offsets).
=> Fix issue 11: Tests work in arbitrary timezones

README.md, database/test/21_shard1/21_schema1/03_types/20_partial_object.sql, database/test/21_shard1/21_schema1/05_stored_procedures/20_get_partial_object.sql, pom.xml, src/main/java/de/zalando/sprocwrapper/SProcCall.java, src/main/java/de/zalando/sprocwrapper/proxy/SProcProxyBuilder.java, src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java, src/main/java/de/zalando/sprocwrapper/proxy/executors/ExecutorWrapper.java, src/main/java/de/zalando/typemapper/annotations/DatabaseField.java, src/main/java/de/zalando/typemapper/annotations/DatabaseType.java, src/main/java/de/zalando/typemapper/core/DatabaseFieldDescriptor.java, src/main/java/de/zalando/typemapper/postgres/PgTypeHelper.java, src/test/java/de/zalando/sprocwrapper/AdvisoryLockTest.java, src/test/java/de/zalando/sprocwrapper/PartialDatabaseTypeIT.java, src/test/java/de/zalando/sprocwrapper/example/ExampleSProcService.java, src/test/java/de/zalando/sprocwrapper/example/ExampleSProcServiceImpl.java, src/test/java/de/zalando/sprocwrapper/example/NotPartialObject.java, src/test/java/de/zalando/sprocwrapper/example/PartialObject.java
Enum usage on AdvisoryLock class is nice but doesn't seem to allow creating new types of locks (correct me if I'm wrong). With this implementation it doesn't look that nice but at least it's extendable.
=> Refactored AdvisoryLock to more extendable form

pom.xml, src/main/java/de/zalando/sprocwrapper/globalobjecttransformer/GlobalObjectTransformerLoader.java
This is needed to use it with Java 8
=> Bumped to newest reflections/javassist version

pom.xml, src/main/java/de/zalando/sprocwrapper/proxy/SProcProxy.java, src/main/java/de/zalando/sprocwrapper/proxy/SProcProxyBuilder.java, src/test/java/de/zalando/sprocwrapper/proxy/SProcProxyBuilderTest.java
Add support to equals/hashCode/toString for dynamic SProc proxy instances
=> Object standard methods support for proxy instances

.gitignore, .travis.yml, pom.xml, test.sh
Updated PostgreSQL version to 9.5.4 for local tests and to 9.5 on travis environment.
Also now travis is skipping javadoc:javadoc task for all non-jvm8 targets and that makes the build green again.
=> Postgres 9.5.4

src/main/java/de/zalando/sprocwrapper/proxy/SProcCallHandler.java, src/main/java/de/zalando/sprocwrapper/proxy/ShardKeyParameter.java, src/main/java/de/zalando/sprocwrapper/proxy/StoredProcedure.java
=> GH-37 Make stored procedure immutable

.travis.yml, pom.xml, src/main/java/de/zalando/sprocwrapper/proxy/OtherStoredProcedureParameter.java, src/main/java/de/zalando/typemapper/core/TypeMapper.java, src/main/java/de/zalando/typemapper/core/fieldMapper/DateFieldMapper.java, src/main/java/de/zalando/typemapper/postgres/PgTypeHelper.java, src/main/java/org/postgresql/jdbc/PostgresJDBCDriverReusedTimestampUtils.java, src/test/java/de/zalando/sprocwrapper/SimpleIT.java, src/test/java/de/zalando/typemapper/postgres/PgSerializerTest.java, src/test/java/de/zalando/typemapper/postgres/PgSerializerToDatabaseTestIT.java
- Update to `spring-4.3.8`
- Update to `postgres-42.1.1`
- Update `pom` version to `2.0.0-SNAPSHOT`
- Fix integration test to support new `postgres` driver version.
=> Update postgres driver and spring versions.

MAINTAINERS, pom.xml
=> Added myself as a maintainer

CONTRIBUTING.md, LICENSE, README.md, pom.xml
* Added contribution guide.
* Changed license to MIT.
* Fixed repository url.
* Fixed readme according to Zalando OSS rules.
=> Project update according to Zalando OSS Rules.

CHANGELOG.MD
Changelog file added with last project updates.
=> Changelog added to project.

README.md, pom.xml
* Fixed `Build status` and `Coverage` badges links.
* Fixed `scm` links and `issueManagement` links in `pom.xml`.
=> Fix repository links after relocation.

.travis.yml, release.sh
=> GH-55 Added relase script

CHANGELOG.MD, pom.xml, src/test/java/org/zalando/typemapper/core/fieldMapper/DoubleFieldMapperTest.java, src/test/java/org/zalando/typemapper/core/fieldMapper/FloatFieldMapperTest.java, src/test/java/org/zalando/typemapper/postgres/HStoreTest.java, src/test/java/org/zalando/typemapper/postgres/PgSerializerTest.java, src/test/java/org/zalando/typemapper/postgres/PgSerializerToDatabaseTestIT.java
* Update `dependency-check-maven` to `6.0.5`
* Update `guava` ([CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908))
* Update `spring` ([CVE-2020-5421](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-5421))
* Update `junit` version
Related to #55
=> Update plugin and dependency versions

.travis.yml
=> Bump to Postgres 13

.github/workflows/workflow.yml, src/test/java/org/zalando/sprocwrapper/SimpleIT.java
* Add Postgres container and run integration tests
* Add caching for maven dependencies
* Fix one integration test to work in different timezones
Integration tests are disabled for the moment. Many tests are failing because of incorrect tests with date times. (see #75 )
Fixes #74
=> Integrate with Github Actions

database/test/21_shard1/21_schema1/03_types/30_example_enum_domain_object.sql, database/test/21_shard1/21_schema1/04_tables/40_enum_example_table.sql, database/test/21_shard1/21_schema1/05_stored_procedures/20_get_example_enum.sql, database/test/21_shard1/21_schema1/05_stored_procedures/20_list_example_enum_domain_objects.sql, pom.xml, src/test/java/org/zalando/sprocwrapper/SimpleIT.java, src/test/java/org/zalando/sprocwrapper/example/ExampleEnumDomainObject.java, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcService.java, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcServiceImpl.java
=> Test for List<EnumType>

.github/workflows/workflow.yml, src/test/java/org/zalando/sprocwrapper/proxy/SProcServiceAnnotationHandlerTest.java
=> Add integration step.

src/test/java/org/zalando/sprocwrapper/SimpleIT.java
=> Fixing the behavior for pg13.

database/test/21_shard1/21_schema1/05_stored_procedures/52_return_enum_from_function.sql, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcService.java, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcServiceImpl.java, src/test/java/org/zalando/typemapper/namedresult/EnumTestIT.java
Add integration test which returns an enum from a function.
References #72
=> Add test which returns enum from a function

src/test/java/org/zalando/typemapper/postgres/PgSerializerToDatabaseTestIT.java
=> Fix integration test

database/test/21_shard1/22_schema3/00_create_schema.sql, database/test/21_shard1/22_schema3/03_types/10_color_enum.sql, database/test/21_shard1/22_schema3/03_types/20_car_domain_object.sql, database/test/21_shard1/22_schema3/03_types/30_customer_address.sql, database/test/21_shard1/22_schema3/03_types/40_customer.sql, database/test/21_shard1/22_schema3/05_stored_procedures/10_list_cars.sql, database/test/21_shard1/22_schema3/05_stored_procedures/20_list_customers.sql, docker-compose.yml, pom.xml, src/main/java/org/zalando/typemapper/core/TypeMapper.java, src/main/java/org/zalando/typemapper/core/fieldMapper/EnumerationFieldMapper.java, src/main/java/org/zalando/typemapper/core/fieldMapper/FieldMapperRegister.java, src/main/java/org/zalando/typemapper/core/fieldMapper/ObjectFieldMapper.java, src/main/java/org/zalando/typemapper/core/result/ObjectResultNode.java, src/main/java/org/zalando/typemapper/core/result/SimpleResultNode.java, src/test/java/org/zalando/sprocwrapper/SimpleIT.java, src/test/java/org/zalando/sprocwrapper/example/Car.java, src/test/java/org/zalando/sprocwrapper/example/Color.java, src/test/java/org/zalando/sprocwrapper/example/Customer.java, src/test/java/org/zalando/sprocwrapper/example/CustomerAddress.java, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcService.java, src/test/java/org/zalando/sprocwrapper/example/ExampleSProcServiceImpl.java, src/test/java/org/zalando/typemapper/namedresult/CollectionWithEnumsTestIT.java, src/test/resources/log4j.xml
* Fix the mapping bug related to enum database types which are located in the schema not in the search path (see [this change](https://github.com/zalando-stups/java-sproc-wrapper/pull/86/files#diff-039a918603445240aa3ab210ca5c24dca122937c461d2f269f200d55dadfa037R76-R82))
* Add additional logging and integration tests for the use case when the schema is not in the search path.
* Cleanup the Java 8 code
* Fix typo in the class name.
Fixes #69
=> Fix a bug with enum type mapping from explicit schema

.mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Fix maven wrapper and update maven version to 3.8.1
=> Fix maven wrapper

README.md, pom.xml, test.sh
=> Update README and test postgres version

cve-suppressions.xml, pom.xml, src/main/java/org/zalando/typemapper/core/TypeMapper.java, src/main/java/org/zalando/typemapper/core/db/DbFunctionRegister.java, src/main/java/org/zalando/typemapper/core/db/DbType.java, src/main/java/org/zalando/typemapper/core/db/DbTypeField.java, src/main/java/org/zalando/typemapper/core/db/DbTypeRegister.java, src/main/java/org/zalando/typemapper/core/result/ArrayResultNode.java, src/main/java/org/zalando/typemapper/core/result/ObjectResultNode.java, src/main/java/org/zalando/typemapper/postgres/PgRow.java
- Use long everywhere a oid is used - adapted from https://github.com/zalando-stups/java-sproc-wrapper/pull/59
- Upgrade the postgres driver
- fix tests
has been tested in ZMON - where the problem actually existed.
=> Use long everywhere a oid is used

.github/workflows/workflow.yml, pom.xml, src/main/java/org/zalando/typemapper/postgres/PgTypeHelper.java
* Backport sources to Java 8
* Switch JDK in the workflow
=> Backport to java 8

pom.xml, src/main/java/org/zalando/sprocwrapper/globalvaluetransformer/GlobalValueTransformerLoader.java
downgrade reflections because of a known bug: https://github.com/ronmamo/reflections/issues/279
=> downgrade reflections
